library(tibble)

extra_read_codes <- tribble(
  ~read_code, ~read_term,
  '136..', 'Alcohol intake',
  '242..', 'O/E - pulse rate',
  '2431.', 'O/E - pulse rhythm regular',
  '246..', 'O/E - blood pressure reading',
  '2469.', 'O/E - Systolic BP reading',
  '246A.', 'O/E - Diastolic BP reading',
  '339A.', 'Peak flow rate before bronchodilation',
  'XaEHe', 'Peak flow rate before bronchodilation',
  '6636.', 'Inhaler technique shown',
  '6637.', 'Inhaler technique observed',
  '663g0', 'Not using inhaled steroids',
  '663g1', 'Using inhaled steroids - normal dose',
  '663H.', 'Inhaler technique - good',
  '663l.', 'Spacer device in use',
  'XaEES', 'Spacer device in use',
  '663L.', 'Bronchodilators used more than once daily',
  '663M.', 'Bronchodilators used a maximum of once daily',
  '663S.', 'Peak flow meter at home',
  '8B314', 'Medication review',
  '8B3x.', 'Medication review with patient',
  '8CAL.', 'Smoking cessation advice',
  'Ua1Nz', 'Smoking cessation advice',
  'X773s', 'Pulse rate',
  'X77RW', 'Serial peak expiratory flow rate',
  'XaF8d', 'Medication review done',
  '66CB.', 'Ideal weight',
  '66Y4.', 'Inhaler technique - moderate',
  'XaIQ0', 'Inhaler technique - moderate',
  '8CA4.', 'Dietary advice',
  '67H..', 'Lifestyle counselling',
  'XaEFY', 'Lifestyle counselling',
  '8B3E.', 'Drug compliance good',
  '44YA0', 'Oxygen saturation at periphery',
  'X770D', 'Oxygen saturation at periphery',
  '8CA5.', 'Patient advised about exercise',
  '8B3V.', 'Medication review done',
  '1711.', 'No cough',
  '663n.', 'Asthma treatment compliance satisfactory',
  '663z.', 'Number of times bronchodilator used in one week',
  '44P5.', 'Serum HDL cholesterol level',
  '1718.',	'Night cough absent',
  '173E.', 'Wheeze absent',
  '8CAM.', 'Patient advised about alcohol',
  '339B.', 'Peak flow rate after bronchodilation',
  '1717.', 'Night cough present',
  'XE2q5', 'Serum creatinine level',
  '44J3.',	'Serum creatinine level',
  'XE2q0', 'Serum sodium level',
  '44I5.', 'Serum sodium level',
  'XE2qz',	'Urine ethanol level',
  'XaK8y', 'GFR calculated abbreviated MDRD',
  '451E.', 'GFR calculated abbreviated MDRD',
  '663g3',	'Increases inhaled steroids appropriately',
  'XaPjx', 'Brief intervention for physical activity completed',
  '9Oq3.', 'Brief intervention for physical activity completed',
  '663g2', 'Using inhaled steroids - high dose',
  '38D4.', 'Alcohol use disorder identification test consumption questionnaire',
  '663I.', 'Inhaler technique - poor',
  '44I4.', 'Serum potassium',
  'XE2pz',	'Serum potassium',
  '1383.',	'Enjoys light exercise',
  'XE2eD', 'Serum cholesterol level',
  'XM0lt', 'Serum urea level',
  '44J9.',	'Serum urea level',
  'XE2eA',	'Serum albumin level',
  '44M4.',	'Serum albumin level',
  'XE2px', 'Serum alkaline phosphatase level',
  '44P6.', 'Serum LDL cholesterol level',
  '1731.', 'No breathlessness',
  '44PF.', 'Total cholesterol:HDL ratio',
  'XaIxD', 'Peak expiratory flow rate monitoring',
  'XaLJx', 'Serum alanine aminotransferase level',
  'XaINi', 'Number of times bronchodilator used in one week',
  'XaIdY', 'Total white blood count',
  '13J..', 'Employment milestones',
  '42P..',	'Platelet count - observation',
  '42A..',	'Mean cell volume',
  '426..',	'Red blood cell count',
  '42J..',	'Neutrophil count',
  '42M..',	'Lymphocyte count',
  '42N..',	'Monocyte count - observation',
  '42L..',	'Basophil count',
  '424..',	'Full blood count',
  '429..',	'Mean cell haemoglobin concentration',
  '44GB.',	'Serum alanine aminotransferase level',
  'Xa96v',	'Haemoglobin concentration',
  'X77Wi',	'Urea and electrolytes',
  '42H..',	'White blood cell count - observation',
  '42F..',	'RBC - red blood cell clumping',
  '44F..',	'Serum alkaline phosphatase',
  '428..',	'Mean corpusc. haemoglobin(MCH)',
  'XE2pb',	'Mean cell haemoglobin level',
  '423..',	'Haemoglobin estimation',
  '44P..',	'Serum cholesterol',
  'X77WP',	'Liver function tests',
  '6799.',	'Health education - diet',
  '3391.',	'Respiratory flow rate measured',
  '66YV.',	'Does not use spacer device',
  'XaPbt',	'Haemoglobin A1c level - IFCC standardised',
  '173I.',	'MRC Breathlessness Scale: grade 2',
  '1FA..',	'Diet good',
  '339g.',	'Serial peak expiratory flow rate',
  '663Z0',	'Bronchodilator used infrequently',
  'XaJCO',	'Medication review with patient',
  'XaERu',	'Serum total bilirubin level',
  '173H.',	'MRC Breathlessness Scale: grade 1',
  '9....', 	'Administration',
  '6798.',	'Health ed. - exercise',
  'XE2q9',	'Serum triglyceride levels',
  'XE2e9',	'Serum total protein level',
  '44D6.',	'Liver function tests',
  'XaPP8',	'GPPAQ physical activity index: inactive',
  '66Z..',	'Chronic dis. monitoring NOS',
  '4258.',	'Haematocrit',
  'X76tb',	'Haematocrit',
  '9N11.',	'Seen in GPs surgery',
  '6896.',	'Depression screening using questions',
  '44EC.',	'Serum total bilirubin level',
  'XaELV',	'Serum TSH level',
  '9N3G.',	'Short message service text message sent to patient',
  '6635.',	'Increasing exercise wheeze',
  'XE2q7',	'Serum lipid levels',
  '138X.',	'GPPAQ physical activity index: inactive',
  '42W5.',	'Haemoglobin A1c level - IFCC standardised',
  '1712.',	'Dry cough',
  '4672.',	'Urine protein test negative',
  '662d.', 'Hypertension annual review',
  '38DP.',	'QRISK2 cardiovascular disease 10 year risk score',
  'XaEJK',	'Blood sample taken',
  '12D2.',	'FH: Asthma',
  '44Q..',	'Serum triglycerides',
  '1FC..',	'Diet average',
  '442W.',	'Serum TSH level',
  'XaEGA', 	'Peak expiratory flow rate after bronchodilation',
  '4662.',	'Urine glucose test negative',
  '44JB.',  'Urea and electrolytes',
  '38D3.',	'Alcohol use disorders identification test',
  '44M3.',	'Serum total protein',
  'XaIul',	'Left dorsalis pedis doppler pressure',
  'XaIUl',	'MRC Breathlessness Scale: grade 2',
  '66Y9.',	'Step up change in asthma management plan',
  'XaIPs',	'Good compliance with inhaler',
  '1384.',	'Enjoys moderate exercise',
  '6792.',	'Health education - alcohol',
  '8BIg.',	'Patient understands why taking all medication',
  'XE2eB',	'Serum globulin level',
  '44O..',	'Serum lipids',
  '138B.',	'Aerobic exercise 3+ times/week',
  '44E..',	'Serum bilirubin level',
  '24F8.',	'O/E - L.dorsalis pedis present',
  'XE2mO',	'Red blood cell distribution width',
  '24E8.',	'O/E - R.dorsalis pedis present',
  'G20..',	'Essential hypertension',
  '8B3S.',	'Medication review',
  '66YA.',	'Step down change in asthma management plan',
  '9c0C.',	'Result',
  '4692.',	'Urine blood test = negative',
  '6791.',	'Health ed. - smoking',
  'XaEUq',	'Serum cholesterol/HDL ratio',
  'XaIeH',	'O/E - Right diabetic foot at low risk',
  '8CAw.',	'Advice about long acting reversible contraception',
  'XaIeL',	'O/E - Left diabetic foot at low risk',
  'XaINj',	'Number of times bronchodilator used in 24 hours',
  'X7708',	'Blood oxygen saturation',
  '1361.',	'Teetotaller',
  '663..',	'Respiratory disease monitoring',
  '9N1d.',	'Seen in asthma clinic',
  '6A...',	'Patient reviewed',
  'XaQVY',	'QRISK2 cardiovascular disease 10 year risk score',
  '44YA.',	'Blood oxygen saturation',
  '8B3d.',	'Good compliance with inhaler',
  '2G5E.',	'O/E - Right diabetic foot at low risk',
  '2G5I.',	'O/E - Left diabetic foot at low risk',
  '68N5.',	'Full consent for immunisation',
  'XaPnn',	'Advice about long acting reversible contraception',
  'XaIUi',	'MRC Breathlessness Scale: grade 1',
  '1362.',	'Trivial drinker - <1u/day',
  '138b.',	'GPPAQ physical activity index: active',
  '66YX.',	'Peak expiratory flow rate monitoring',
  '138a.',	'GPPAQ physical activity index: moderately active',
  '173J.',	'MRC Breathlessness Scale: grade 3',
  '4682.',	'Urine ketone test negative',
  'XaIUg',	'Positive reversibility test to salbutamol',
  '173J.',	'MRC Breathlessness Scale: grade 3',
  '42Z7.',	'Red blood cell distribution width',
  '24F6.',	'O/E - L.post.tib.pulse present',
  'XaX3o',	'Diabetic dietary review',
  '3371.',	'Lung function testing done',
  'Xa8Pl',	'Cervical smear',
  '662P.',	'Hypertension monitoring',
  'XE2n3',	'Urine albumin/creatinine ratio',
  'XaQaV',	'Lifestyle advice regarding hypertension',
  '46TC.',	'Urine albumin:creatinine ratio',
  'XE2xQ',	'Peak flow rate before bronchodilation',
  '339D.',	'Best ever peak flow rate',
  '44IC.',	'Corrected serum calcium level',
  '138Y.',	'GPPAQ physical activity index: moderately inactive',
  'XaORP',	'Alcohol use disorder identification test consumption questionnaire',
  '29BC.',	'10g monofilament sensation L foot normal',
  '29BB.',	'10g monofilament sensation R foot normal',
  'XM1Xu',	'Drugs - partial non-compliance',
  '41D0.',	'Blood sample taken',
  '388B.',	'Pack years',
  '1737.',	'Wheezing',
  '44g..',	'Plasma glucose level',
  'XaG5t',	'Main spoken language English',
  '44M5.',	'Serum globulin',
  '13l4.',	'Main spoken language English',
  'XaIyE',	'Hypertension annual review',
  '13A..',	'Patient-initiated diet',
  'XE2mj',	'Serum electrolyte levels',
  '66A4.',	'Diabetic on oral treatment',
  'X77Wg',	'Thyroid function test',
  'XE0ps',	'Self-help group membership',
  '661Q.',	'Chronic disease annual review',
  'XaKTi',	'Liquid based cervical cytology screening',
  '44G9.',	'Serum gamma-glutamyl transferase level',
  '137G.',	'Trying to give up smoking',
  '4266.',	'Nucleated red blood cell count',
  'XaIUm',	'MRC Breathlessness Scale: grade 3',
  '46M7.',	'Urine creatinine',
  '8CL..',	'Discussion about disorder',
  '892..',	'Informed consent for procedure',
  'XaPPE',	'GPPAQ physical activity index: active',
  '138..',	'Exercise grading',
  '8I6L.',	'Spirometry not indicated',
  'XaIeG',	'10g monofilament sensation L foot normal',
  '8CP..',	'Discussion about treatment',
  'XaIeF',	'10g monofilament sensation R foot normal',
  '171..',	'Cough',
  'Xa041',	'Waist circumference',
  'XE2rN',	'Best ever peak flow rate',
  '66At.',	'Diabetic dietary review',
  'X77cx',	'Pulse oximetry',
  'XE2q0',	'Serum sodium level',
  '1713.',	'Productive cough -clear sputum',
  '9N31.',	'Telephone encounter',
  'XaLIc',	'Depression screening using questions',
  '24E6.',	'O/E - R.post.tib.pulse present',
  'XE0ps',	'Self-help group membership',
  'XE2q0',	'Serum sodium level',
  '44lF.',	'Serum cholesterol/HDL ratio',
  'XaCIx',	'Diet good',
  '33H1.',	'Positive reversibility test to salbutamol',
  '9b30.',	'Scanned document',
  'XaMiI',	'Short message service text message sent to patient',
  '68S..',	'Alcohol consumption screen',
  'XaX3q',	'Type II diabetic dietary review',
  'XE2q1',	'Serum chloride level',
  'XaJHr',	'Has shown no side effects from medication',
  'XaIuB',	'Does not use spacer device',
  '4K22.',	'Cervical smear: negative',
  '4....',	'Laboratory procedures',
  '442V.',	'Serum free T4 level',
  '44g1.',	'Plasma fasting glucose level',
  '67H8.',	'Lifestyle advice regarding hypertension',
  '8BMJ.',	'Dispensing review of use of medicines',
  'XaPPD',	'GPPAQ physical activity index: moderately active',
  'XE2q3',	'Serum calcium level',
  '66A..',	'Diabetic monitoring',
  'Ua1Qa',	'Symptom control',
  'XaERr',	'Serum free T4 level',
  'XaIUk',	'Positive reversibility test to corticosteroids',
  '42U5.',	'Serum folate level',
  '137n.',	'Total time smoked',
  '8HRC.',	'Referral for spirometry',
  'XM1Yn',	'Influenza immunisation advised',
  'XaFvp',	'Patient advised about alcohol',
  '44Z2.',	'Bone profile',
  'XE1TH',	'Counselling, advice and education',
  '66At1',	'Type II diabetic dietary review',
  'XM02J',	'Pulse regular',
  'XaCH9',	'Wheeze absent',
  '38Dg.',	'Chronic obstructive pulmonary disease assessment test',
  '42I..',	'Differential white blood cell count',
  'XaJIt',	'Lifestyle advice regarding exercise',
  'XaEYo',	'Urine nitrite negative',
  'XE2q2',	'Serum bicarbonate level',
  '21262',	'Asthma resolved',
  '44I8.',	'Serum calcium',
  '661M.',	'Clinical management plan agreed',
  '61...',	'Contraception',
  'XaQaU',	'Lifestyle advice regarding diet',
  'Xa1qL',	'Consultation',
  '8A44.',	'Pulse oximetry monitoring',
  'XE0pS',	'Employment milestones',
  'XE2qO',	'Urine creatinine level',
  '235..',	'O/E - rate of respiration',
  '7E2A2',	'Papanicolau smear NEC',
  '442J.',	'Thyroid function test',
  'XM0ly',	'Plasma glucose level',
  '6774.',	'Medication counselling',
  '663Z1',	'Bronchodilator not used in last month',
  '6633.',	'Oral steroids last used',
  "663J.",	'Airways obstruction reversible',
  '663T.',	'No peak flow meter at home',
  '6638.', 	'Home nebuliser',
  '663B.',	'Resp. treatment changed',
  '663g4',	'Using inhaled steroids - low dose',
  '663K.',	'Airways obstructn irreversible',
  '663g.',	'Inhaled steroids use',
  '663c.',	'Nebulisation since last appointment',
  '663Y.',	'Steroid dose inhaled daily',
  '6631.',	'Initial resp. assessment',
  '663F.',	'Oral steroids started',
  '663A.',	'Resp. drug side effects',
  '6632.',	'Follow-up resp. assessment',
  '6639.',	'Home oxygen supply',
  '663o.',	'Declined to perform inhaler technique',
  '663b.',	'Home nebuliser used since last appointment',
  '663Z.',	'Resp. disease monitoring NOS',
  '663k.',	'Reversibility trial by steroids',
  '663G.',	'Oral steroids stopped',
  '388u.',	'Fast alcohol screening test'
  )

saveRDS(extra_read_codes,  'codes/extra_read_codes.RDS', compress = FALSE)
